package report

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// FormatMarkdown formats the report data as Markdown.
func FormatMarkdown(data *ReportData) string {
	var sb strings.Builder
	
	// Header
	sb.WriteString("# Network Pulse Report\n\n")
	sb.WriteString(fmt.Sprintf("**Generated:** %s\n\n", data.GeneratedAt.Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("**Period:** %s to %s\n\n",
		data.Since.Format("2006-01-02 15:04"),
		data.Until.Format("2006-01-02 15:04")))
	sb.WriteString("---\n\n")
	
	// Executive Summary
	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Metric | Value |\n")
	sb.WriteString("|--------|-------|\n")
	if data.CurrentIP != nil {
		sb.WriteString(fmt.Sprintf("| Current IP | `%s` |\n", data.CurrentIP.IP))
		sb.WriteString(fmt.Sprintf("| ISP | %s |\n", data.CurrentIP.ISP))
	}
	sb.WriteString(fmt.Sprintf("| IP Changes | %d |\n", data.IPChangeCount))
	sb.WriteString(fmt.Sprintf("| Trace Changes | %d |\n", len(data.TraceChanges)))
	sb.WriteString(fmt.Sprintf("| Alive Hosts | %d |\n", data.AliveCount))
	sb.WriteString(fmt.Sprintf("| Open Ports | %d |\n", data.PortCount))
	sb.WriteString("\n")
	
	// IP History Section
	sb.WriteString("## IP Address History\n\n")
	if len(data.IPChanges) > 0 {
		sb.WriteString("### IP Changes Detected\n\n")
		sb.WriteString("| Time | Old IP | New IP |\n")
		sb.WriteString("|------|--------|--------|\n")
		for _, change := range data.IPChanges {
			sb.WriteString(fmt.Sprintf("| %s | `%s` | `%s` |\n",
				change.Timestamp.Format("01-02 15:04"),
				change.OldIP, change.NewIP))
		}
		sb.WriteString("\n")
	} else {
		sb.WriteString("No IP changes detected during this period.\n\n")
	}
	
	// Traceroute Section
	sb.WriteString("## Traceroute Analysis\n\n")
	
	if len(data.TraceChanges) > 0 {
		sb.WriteString("### Route Changes Detected\n\n")
		for _, change := range data.TraceChanges {
			sb.WriteString(fmt.Sprintf("#### %s at %s\n\n",
				change.Target, change.Timestamp.Format("01-02 15:04")))
			
			if len(change.Added) > 0 {
				sb.WriteString("**Added hops:** ")
				sb.WriteString(strings.Join(formatHops(change.Added), ", "))
				sb.WriteString("\n\n")
			}
			if len(change.Removed) > 0 {
				sb.WriteString("**Removed hops:** ")
				sb.WriteString(strings.Join(formatHops(change.Removed), ", "))
				sb.WriteString("\n\n")
			}
		}
	}
	
	// Latest traces with diagrams
	if len(data.TracesByTarget) > 0 {
		sb.WriteString("### Current Routes\n\n")
		for target, traces := range data.TracesByTarget {
			if len(traces) > 0 {
				sb.WriteString(fmt.Sprintf("#### Route to %s\n\n", target))
				sb.WriteString(GenerateMermaidDiagram(traces[0]))
				sb.WriteString("\n")
			}
		}
	}
	
	// Network Scan Section
	sb.WriteString("## Network Scan Results\n\n")
	
	if len(data.AliveHosts) > 0 {
		sb.WriteString("### Alive Hosts\n\n")
		sb.WriteString("| IP | Hostname | Latency |\n")
		sb.WriteString("|----|----------|--------|\n")
		for _, host := range data.AliveHosts {
			hostname := host.Hostname
			if hostname == "" {
				hostname = "-"
			}
			sb.WriteString(fmt.Sprintf("| `%s` | %s | %.1f ms |\n",
				host.IP, hostname, host.LatencyMs))
		}
		sb.WriteString("\n")
	} else {
		sb.WriteString("No alive hosts detected.\n\n")
	}
	
	// Port Summary (grouped by host would be too long, summarize)
	if len(data.OpenPorts) > 0 {
		sb.WriteString("### Open Ports Summary\n\n")
		
		// Count ports by service
		serviceCounts := make(map[string]int)
		for _, port := range data.OpenPorts {
			serviceCounts[port.Service]++
		}
		
		sb.WriteString("| Service | Count |\n")
		sb.WriteString("|---------|-------|\n")
		for service, count := range serviceCounts {
			sb.WriteString(fmt.Sprintf("| %s | %d |\n", service, count))
		}
		sb.WriteString("\n")
	}
	
	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by netpulse*\n")
	
	return sb.String()
}

func formatHops(hops []string) []string {
	formatted := make([]string, len(hops))
	for i, hop := range hops {
		formatted[i] = fmt.Sprintf("`%s`", hop)
	}
	return formatted
}

// WriteMarkdownFile writes the markdown report to a file.
func WriteMarkdownFile(data *ReportData, outputDir string) (string, error) {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create output dir: %w", err)
	}
	
	filename := fmt.Sprintf("report_%s.md", data.GeneratedAt.Format("2006-01-02_15-04"))
	filepath := filepath.Join(outputDir, filename)
	
	content := FormatMarkdown(data)
	
	if err := os.WriteFile(filepath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("failed to write report: %w", err)
	}
	
	return filepath, nil
}
